name: Build and Deploy
run-name: Build and deploy docker images on dockerhub

on: [push, workflow_dispatch]
jobs:
    build_job:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Autenticate with Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Build Alpine-novnc Base
            run: docker build -t alpine-novnc:base Base/.

          - name: Push Alpine-novnc Base
            run: |
              docker tag alpine-novnc:base "${{ secrets.DOCKERHUB_USERNAME }}/alpine-novnc:base"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/alpine-novnc:base"

          - name: Build Alpine-novnc Fluxbox
            run: docker build -t alpine-novnc:fluxbox Fluxbox/.

          - name: Push Alpine-novnc Fluxbox
            run: |
              docker tag alpine-novnc:fluxbox "${{ secrets.DOCKERHUB_USERNAME }}/alpine-novnc:fluxbox"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/alpine-novnc:fluxbox"
